### ISSUE TITLE
ext.videoJs.videoJs error

### ISSUE THREAD

**Issue by JeXawoW** [ychoucha/videoJs#4]
exception 'CException' with message '"ext.videoJs.videoJs" geçersiz bir alias. Varolan bir php dosyasına işaret ettiğine emin olun.' in /home/xxxxx/public_html/protected/vendors/yii/YiiBase.php:322 Stack trace: #0 /home/xxxxx/public_html/protected/vendors/yii/web/CWidgetFactory.php(146): YiiBase::import('ext.videoJs.vid...', true) #1 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(146): CWidgetFactory->createWidget(Object(ShowFilesWidget), 'ext.videoJs.vid...', Array) #2 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(172): CBaseController->createWidget('ext.videoJs.vid...', Array) #3 /home/xxxxx/public_html/protected/modules_core/file/widgets/views/showFiles.php(54): CBaseController->widget('ext.videoJs.vid...', Array) #4 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(130): require('/home/xxxxx/...') #5 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal('/home/xxxxx/...', Array, false) #6 /home/xxxxx/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): CBaseController->renderFile('/home/xxxxx/...', Array, false) #7 /home/xxxxx/public_html/protected/modules_core/file/widgets/ShowFilesWidget.php(29): CWidget->render('showFiles', Array) #8 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(167): ShowFilesWidget->run() #9 /home/xxxxx/public_html/protected/widgets/StackWidget.php(94): CBaseController->widget('application.mod...', Array, true) #10 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(173): StackWidget->run() #11 /home/xxxxx/public_html/protected/modules_core/wall/views/wallLayout.php(71): CBaseController->widget('application.mod...', Array) #12 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(126): require('/home/xxxxx/...') #13 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal('/home/xxxxx/...', Array, true) #14 /home/xxxxx/public_html/protected/vendors/yii/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/home/xxxxx/...', Array, true) #15 /home/xxxxx/public_html/protected/vendors/yii/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate(' <span i...') #16 /home/xxxxx/public_html/protected/vendors/yii/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput(' <span i...') #17 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(206): COutputProcessor->run() #18 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...') #19 /home/xxxxx/public_html/protected/modules_core/post/widgets/views/post.php(23): CBaseController->endContent() #20 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(130): require('/home/xxxxx/...') #21 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(95): CBaseController->renderInternal('/home/xxxxx/...', Array, false) #22 /home/xxxxx/public_html/protected/vendors/yii/web/widgets/CWidget.php(244): CBaseController->renderFile('/home/xxxxx/...', Array, false) #23 /home/xxxxx/public_html/protected/modules_core/post/widgets/PostWidget.php(38): CWidget->render('post', Array) #24 /home/xxxxx/public_html/protected/vendors/yii/web/CBaseController.php(167): PostWidget->run() #25 /home/xxxxx/public_html/protected/modules_core/post/models/Post.php(113): CBaseController->widget('application.mod...', Array, true) #26 /home/xxxxx/public_html/protected/modules_core/wall/BaseStreamAction.php(253): Post->getWallOut() #27 /home/xxxxx/public_html/protected/vendors/yii/web/actions/CAction.php(76): BaseStreamAction->run() #28 /home/xxxxx/public_html/protected/vendors/yii/web/CController.php(308): CAction->runWithParams(Array) #29 /home/xxxxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(133): CController->runAction(Object(ContentContainerStreamAction)) #30 /home/xxxxx/public_html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #31 /home/xxxxx/public_html/protected/vendors/yii/web/CController.php(1145): CFilter->filter(Object(CFilterChain)) #32 /home/xxxxx/public_html/protected/vendors/yii/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain)) #33 /home/xxxxx/public_html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain)) #34 /home/xxxxx/public_html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #35 /home/xxxxx/public_html/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(Object(ContentContainerStreamAction), Array) #36 /home/xxxxx/public_html/protected/vendors/yii/web/CWebApplication.php(282): CController->run('stream') #37 /home/xxxxx/public_html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('space/space/str...') #38 /home/xxxxx/public_html/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #39 /home/xxxxx/public_html/index.php(39): CApplication->run() #40 {main} REQUEST_URI=/s/e2f97f69-5aab-4a69-a7a8-ef41a9cd189a/space/space/stream/limit/4/filters//sort/c/from//mode/normal?CSRF_TOKEN=4ea00dbb94b5bde66b23e374c9fe39672b0d488d&_=1429173605108 HTTP_REFERER=http://www.xxxxx.com/s/e2f97f69-5aab-4a69-a7a8-ef41a9cd189a/home ---

**Comment by ychoucha** [comment]
How u have that ?

**Comment by JeXawoW** [comment]
I un name correction, sorry
![1](https://cloud.githubusercontent.com/assets/7725575/7216249/46f0a262-e601-11e4-833f-d677d6c2a286.PNG)
